In [5]:
import numpy
numpy.__version__

'1.17.2'

In [12]:
import numpy as np

a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [13]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [14]:
a = np.zeros((2,2)) # 모든 값이 0인 2x2 array 생성
print(a)

[[0. 0.]
 [0. 0.]]


In [15]:
b = np.ones((1,2)) # 모든 값이 1인 1x2 array 생성
print(b)

[[1. 1.]]


In [16]:
c = np.full((2,2), 7) # 모든 값이 7인 2x2 array 생성
print(c)

[[7 7]
 [7 7]]


In [17]:
d = np.eye(2) # 2x2 단위행렬(Identity matrix) 생성
print(d)

[[1. 0.]
 [0. 1.]]


In [18]:
e = np.random.random((2,2)) # 0~1 랜덤 값을 가지는 2x2 array 생성
print(e)

[[0.02991802 0.77300206]
 [0.56018699 0.81696103]]


In [19]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
b = a[:2, 1:3]
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])

2
77


In [21]:
b=a[:,1] # 모든 행 선택
print(b)

[77  6 10]


In [22]:
import numpy as np
# 2차원 배열(3x4) 생성
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# 두 번째 행의 값들을 모두 가져오는 두 가지 방법
row_r1 = a[1, :] # 1차원 행렬 (4,)
row_r2 = a[1:2, :] # 2차원 행렬 (1x4) – 기존 차원 유지
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
# 두 번째 열의 값들을 모두 가져오는 두 가지 방법
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [34]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
b=np.array([a[0,0], a[1,1], a[2,0]])
print(b)
print(b.shape)

print(a[[0,1,2],[0,1,0]])


[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
(3,)
[1 4 5]


In [41]:
# 2차원 배열(4x3) 생성
# [[ 1 2 3]
# [ 4 5 6]
# [ 7 8 9]
# [ 10 11 12]]
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b]) #  a[ [0,1,2,3], [0,2,0,1]] 0,1,2,3과 0,2,0,1열

[ 1  6  7 11]


In [40]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [32]:
a[np.arange(4), b] += 10
print(a) # array([[11, 2, 3],
# [ 4, 5, 16],
# [17, 8, 9],
# [10, 21, 12]])

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [33]:
x = np.array([1, 2])
print(x.dtype) # prints “int64”
x = np.array([1.0, 2.0])
print(x.dtype) # “float64”
x = np.array([1, 2], dtype=np.int64) # 데이터타입 명시
print(x.dtype) # “int64”

int64
float64
int64


In [36]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [42]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
# v · w = 219
print(v.dot(w))
print(np.dot(v, w))
# 매트릭스 / 벡터 곱; [29 67]
print(x.dot(v))
print(np.dot(x, v))
# 매트릭스 / 매트릭스 곱;
# [[19 22]
# [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [43]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
print(np.sum(x)) # 모든 원소의 합
print(np.sum(x, axis=0)) # 각 열의 합
print(np.sum(x, axis=1)) # 각 행의 합

10
[4 6]
[3 7]


In [44]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T) # 전치행렬 (Transposed mat.)
v = np.array([1,2,3])
print(v) # prints “[1 2 3]”
print(v.T) # prints “[1 2 3]” 벡터는 그대로 나온다.

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [47]:
a=np.ones((2,3,4))
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=0).shape)

24.0
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
(3, 4)


In [52]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x) # x와 같은 shape의 빈 매트릭스 만들기
# x의 각 행에 v와 elementwise 합을 하여 y의 해당 행에 할당
for i in range(4):
    y[i, :] = x[i, :] + v
# [[ 2 2 4]
# [[ 5 5 7]
# [[ 8 8 10]
# [ 11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [53]:
vv = np.tile(v, (4, 1)) # v 내용을 4x1의 각 행에 반복함 / for 보다 빠름 
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [54]:
y = x + vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
(2,3,4) (1,3,1) #마지막이 2라서 브로드캐스팅이 안됨
(4,3) (3,) # 이건 됨. 제일 뒤에 있는 엑시스랑 아귀가 맞으면 됨
(3,4) (3,) # 행에 대해서 변경(열에 대한 축을 만들기) => (3,1)
x.reshape((3,1))
x[:,None] # None 을 써서 축을 새로 만든다.

In [55]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
# 브로드캐스팅을 사용하여 x의 각 행에 v값을 더함
y = x + v
# [[ 2 2 4]
# [[ 5 5 7]
# [[ 8 8 10]
# [ 11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [56]:
a=np.array([1,2,3])
a1=a.reshape([3,1])
print(a1.shape)

a2=a[:, None]


(3, 1)


In [77]:
import numpy as np

l=np.array([[1,1],[2,1]])
r=np.array([15,25])
i=np.linalg.inv(l)

print(i.shape)
print(i)
print(r.shape)
print(r)

m=i.dot(r)
print(m)

(2, 2)
[[-1.  1.]
 [ 2. -1.]]
(2,)
[15 25]
[10.  5.]
[10  5]


In [81]:
import numpy as np
x1 = np.array([0,0])
x2 = np.array([0,1])
x3 = np.array([1,0])
x4 = np.array([1,1])

In [84]:
무작위 샘플링+무한 루프
w, b의 값을 랜덤
0001이 나오면 break

[0 0]


In [85]:
import pandas as pd


In [ ]:
    def print_info(self):
        ls = []
        for i in range(len(self.student)):
            if i == len(self.student) -1:
                ls.append(i)
                print("%s" %i, end = '')
            else:
                ls.append(i)
                print("%s" %i, end = ', ')
        print("제 이름은 '+self.name+', 나이는 '")
        